### ISSUE TITLE
npm install atui --save It can't work

### ISSUE THREAD

**Issue by hpym365** [aliqin/atui#10]
I created my project by vue-cli webpack template
and install atui .
`npm install atui --save`
Then I created a vue file 
```
<template>
  <div>
    <Alert></Alert>
  </div>
</template>
<script>
  import atui from 'atui'
  export default{
    components: {
      Alert: atui.Alert
    }
  }
</script>

```
when I compiled the code , 2 warnings

>  warning  in ./~/atui/dist/atui.js
> 
> Critical dependencies:
> 7:82-97 the request of a dependency is an expression
> 
>  @ ./~/atui/dist/atui.js 7:82-97
> 
>  warning  in ./~/atui/dist/atuiFilter.js
> 
> Critical dependencies:
> 7:82-97 the request of a dependency is an expression
> 
>  @ ./~/atui/dist/atuiFilter.js 7:82-97

And I use chrome open the url localhost:8080  
![1](https://cloud.githubusercontent.com/assets/22383462/22850912/4ea6ed00-f04e-11e6-8b9b-8ab4be974e42.png)

![2](https://cloud.githubusercontent.com/assets/22383462/22850905/3028adfa-f04e-11e6-9272-132de8f9c67b.png)
It cant work .

**Comment by lynsun** [comment]
v0.0.18 fix
