### ISSUE TITLE
请问现在还不能全局引用组件吗

### ISSUE THREAD

**Issue by cdllqos** [aliqin/atui#12]
在main.js类似element ui 引入
import atui from 'atui'
Vue.use(atui)

我这样引入了，在子组件里使用v-row报错这个组件没有注册

**Comment by lynsun** [comment]
执行`import atui from 'atui'`后所有组件都挂载在atui变量下，布局组件可以通过atui.Layout.Row，atui.Layout.Col获取，不需要再执行`Vue.use(atui)`，可以这样使用：
```html
<v-row>
      <v-col span="23">col-23</v-col>
      <v-col span="1">1</v-col>
</v-row>
```

```javascript
  import atui from 'atui'
  import 'atui/dist/greater-blue.css';
  
  console.log(atui)
  
  export default{
    components: {
      vButton: atui.Button,
      vRow: atui.Layout.Row,
      vCol: atui.Layout.Col
    }
  }
```

更多demo可以参考 http://aliqin.github.io/src/components/Layout
有问题欢迎反馈，也欢迎参与共建

**Comment by cdllqos** [comment]
这样在局部里注册是可以的，比如常用的一些组件可以在main.js注册，如果较多的组件在main.js里使用vue.component('key',value)这样的方式会不会不太友好。如果在局部组件里使用你说的方式注册，例如vRow,vCol就需要注册很多次了吧，这样重复代码太多了，而且也没有必要。我尝试在main.js通过遍历的方式将全部组件注册，代码如下
`import Vue from 'vue'
import App from './App'
import router from './router'
import atui from 'atui'
for(let i in atui)
  console.log(atui[i])
Vue.component('v-Button',atui.Button)`
但是发现打印的结果有还有一个object对象。这样的方式也不能实现。如果可以希望后续版本增加一个api实现多个组件在main.js里注册

**Comment by lynsun** [comment]
@cdllqos 你提的这个建议不错，后续版本考虑加一个api来自动注册所有组件，但默认不全部注册

**Comment by cdllqos** [comment]
@lynsun 好的，期待。

**Comment by lynsun** [comment]
@cdllqos v0.0.27支持了全局注册组件 
`import atui from 'atui'` 后执行 `Vue.use('atui')`，
组件注册命名方式为`v-xxx` xxx 为组件的name属性`camel2Dash`转换后的值，
比如DatePicker组件注册名为`v-date-picker`

**Comment by cdllqos** [comment]
@lynsun 效率挺高的吧，点个赞

**Comment by cdllqos** [comment]
还是关于全局引用的问题，之前有事以为就这样可以使用了。但是这样引用 Vue.use(atui),浏览器会报
`Uncaught TypeError: Cannot read property 'prefix' of undefined`，我看了下源码，你们是这样写的
`module.exports.install = (Vue, opts) => {
  let prefix = opts.prefix || 'v'
  Object.keys(VueComponent).forEach((key) => {
    // prefix component name with 'v'  <v-button></v-button>
    let comp = VueComponent[key]
    let compName = comp.name
    if (compName) {
      let dashCompName = prefix + '-' + camel2Dash(compName)
      Vue.component(dashCompName, comp)
    }
  })
}`
引用opts 默认没有传参数进去，然后直接调用opts这个对象会报错，如果任意传一个值就不会报错了

**Comment by lynsun** [comment]
@cdllqos 确实，这里没有兼容到不传参数的情况，可以先显式的传递prefix参数，明天会发一个版本修复这个问题，多谢反馈

**Comment by cdllqos** [comment]
@lynsun 辛苦了，期待以后稳定。

**Comment by lynsun** [comment]
@cdllqos v0.0.29发布了，修复了vue.use(atui)的报错，最近支持业务需求，小版本会发的比较频繁，预计月底会发一个稳定版本

**Comment by cdllqos** [comment]
嗯，再观望一段时间，等稳定了再上。加油。
