### ISSUE TITLE
表格自定义展示列

### ISSUE THREAD

**Issue by 95502967** [aliqin/atui#14]
给表格添加自定义展示列，仅显示title，不显示内容，也不报错
![default](https://cloud.githubusercontent.com/assets/26525226/24082665/64e92326-0d04-11e7-8910-9babaced921e.png)

`<style lang="less">
</style>

<template>
  <v-table :data-source="dataSource" :columns="columns">
    <div slot="noDataTip">if dataSource is null, i will displayed</div>
    <template scope="props" :slot="age">
      <span>年龄：{{props.record.age}}</span>
    </template>
    <template scope="props" :slot="operation">
      <v-button @click.native="onBtnClick(props.record)">操作</v-button>
    </template>
  </v-table>
</template>

<script>
	import atui from 'atui';
	const dataSource = [{
		key: '1',
		name: '胡彦斌 ',
		age: 321,
		address: '西湖区湖底公园1号'
	}, {
		key: '2',
		name: '胡彦祖',
		age: 422,
		address: '西湖区湖底公园1号'
	}];

	const columns = [{
		title: '姓名',
		dataIndex: 'name',
		key: 'name',
	}, {
		title: '年龄',
		dataIndex: 'age',
		key: 'age',
	}, {
		title: '住址',
		dataIndex: 'address',
		key: 'address',
	},{
		title: '操作',
		key: 'operation'
	}];
  export default {
	  components: {
		  vTable: atui.Table,
      vButton: atui.Button
	  },
    data() {
      return {
	      dataSource:dataSource,
	      columns:columns
      }
    },
    created() {
      console.log('component c created !');
    },
    methods: {
      //
    }
  }
</script>
`
相关版本：
    "atui": "0.0.30",
    "babel-preset-es2015": "^6.18.0",
    "vue": "^2.1.10",
    "vue-router": "^2.2.0",
    "vueify-insert-css": "^1.0.0"

**Comment by lynsun** [comment]
Table组件的自定义列展示可以这样使用：
```javascript
  // table配置
  const dataSource = [{
    key: '1',
    name: '胡彦斌',
    age: 32,
    address: '西湖区湖底公园1号'
  }, {
    key: '2',
    name: '胡彦祖',
    age: 42,
    address: '西湖区湖底公园1号'
  }];

  const columns = [{
    title: '姓名',
    dataIndex: 'name',
    key: 'name',
  }, {
    title: '年龄',
    dataIndex: 'age',
    key: 'age',
  }, {
    title: '住址',
    dataIndex: 'address',
    key: 'address',
  },{
    title: '操作',
    key: 'operation'
  }];

  export default{
    data() {
      return {
        dataSource: dataSource,
        columns: columns
      }
    },
    methods: {
      onOperate (record) {
        alert('您点击了:'+record.name)
        console.log(record)
      }
    }
  }
```
```html
<template>
  <div>
    <v-table :data-source="dataSource" :columns="columns">
      <div slot="noDataTip">if dataSource is null, i will displayed</div>
      <template scope="props" :slot="age">
        <span>年龄：{{props.record.age}}</span>
      </template>
      <template scope="props" :slot="operation">
        <v-button @click.native="onOperate(props.record)">操作</v-button>
      </template>
    </v-table>
  </div>
</template>
```

需要注意的是，自定义的列需要在列配置中配置下`title`和`key`属性，具体的渲染逻辑在模版中以`scoped slot`的方式自定义
完整的例子可以参考示例项目：
https://github.com/lynsun/vue-pro/blob/master/src/Demo.vue 
或者atui官网的demo源码：
https://github.com/aliqin/atui/blob/dev/src/components/Table/demo/custom.md

有问题随时沟通～

**Comment by 95502967** [comment]
示例项目安装依赖包以后运行有报错，如下
https://github.com/lynsun/vue-pro/blob/master/src/Demo.vue
![default](https://cloud.githubusercontent.com/assets/26525226/24088403/d1873a62-0d64-11e7-8e0c-8ee0c63f1357.png)

**Comment by lynsun** [comment]
`package.json`里`atui`版本号升到`0.0.36`，重新install下

**Comment by 95502967** [comment]
升到0.0.36，还是有报错，
0.0.36，
![default](https://cloud.githubusercontent.com/assets/26525226/24088836/506504a4-0d6a-11e7-826e-7e58c0901999.png)

**Comment by lynsun** [comment]
定位到这个警告在vue@2.2.x上抛出来的，2.1.4下是没问题的，我提了issue给vue团队，https://github.com/vuejs/vue/issues/5230
执行`npm install`目前默认安装的是最新版本的`vue`和`vue-template-compiler`，你可以把`package.json`里关于`vue`和`vue-template-compiler`的版本号从`^2.1.4`改为`2.1.4`，重新安装可以正常运行

**Comment by 95502967** [comment]
好的，感谢~

**Comment by lynsun** [comment]
@95502967 原因找到了
vue2.1.x `scoped slot`可以通过 `:slot=“slotName”` 绑定`slot`名（`slotName`可以是`slot`对应的变量名，也可以是具体的值） 
vue2.2.x下只能通过:slot绑定slot对应的变量名，如果是具体值不应该加冒号（vue本身的设计也是加冒号来绑定变量），换句话说其实是vue2.1.x兼容了使用动态绑定来绑定具体值的写法
在本例中，因为`age`和`operation`是具体的列名而不是变量，所以绑定时不需要加冒号，即需要把`:slot="age"`和`:slot="operation"`改为`slot="age"`和`slot="operation"` 
修改后的demo在vue2.1.x和vue2.2.x下都能正常运行：
http://codepen.io/sugarboy/pen/XMZWoo?editors=1010
