### ISSUE TITLE
menu导航菜单绑定数据bug

### ISSUE THREAD

**Issue by EvanLai0819** [aliqin/atui#17]
使用绑定数据自动渲染时，无法对menu进行show处理，就是无法正常显示我要显示的子菜单

**Comment by lynsun** [comment]
@EvanLai0819 发布了v0.0.39 
Menu组件使用绑定数据自动渲染时可以通过配置MenuItem的`selected: true`来选中该菜单项，SubMenu配置`show: true`来展开当前menuitem所在的子菜单，详情参考官网demo和文档：https://aliqin.github.io/atui/src/components/Menu#Menu动态渲染的数据结构
