### ISSUE TITLE
Menu动态渲染的数据结构问题

### ISSUE THREAD

**Issue by EvanLai0819** [aliqin/atui#19]
在使用Menu动态渲染的数据结构的时候，a标签无法正常被识别，数据结构中我是这样的：

content: '<a href="http://www.alidayu.com" target="_blank">选项1</a>'

**Comment by lynsun** [comment]
目前没有按html来解析，今天发个小版本支持下

**Comment by lynsun** [comment]
发布了v0.0.40，支持content传递html

**Comment by EvanLai0819** [comment]
好像还没发布？我更新都是0.0.39

**Comment by lynsun** [comment]
我这边看是有v0.0.40的tag的，本地更新了可以的呀，可以参考下这个示例项目，用的0.0.40
https://github.com/lynsun/vue-pro/blob/master/src/Demo.vue

**Comment by EvanLai0819** [comment]
再更新一次就好了，谢谢
