### ISSUE TITLE
form表单bug

### ISSUE THREAD

**Issue by EvanLai0819** [aliqin/atui#20]
v-input中minlength-tips无法正常显示

**Comment by lynsun** [comment]
hi,官网我补充了一个关于minlengthTips的demo，我这边看没有问题，可否提供下重现的方式或demo
https://aliqin.github.io/atui/src/components/Input

**Comment by EvanLai0819** [comment]
`<div id="app">

    <v-form action="" method="post">
        <form-item required label="姓名:" valid-status="error" label-col="4" wrapper-col="12" has-icon >
            <v-input type="text" :value="username" placeholder="请输入您的姓名" required required-tips="用户名为必填项" maxlength="5" minlength="4" minlength-tips="用户名不能少于2个字符"  :valid-result="validResult"></v-input>
        </form-item>

        <v-form-item label-col="4" wrapper-col="12">
            <v-button type="submit" primary style="margin-right:10px">确定</v-button>
            <v-button type="reset" tertiary value="重置条件"></v-button>
        </v-form-item>
    </v-form>
</div>`

不能把错误正确显示在文本框下方

**Comment by lynsun** [comment]
错误信息在绑定的变量里面，需要自己加一个标签输出，可以参考官网这个demo的源码：
https://github.com/aliqin/atui/blob/v0.0.40/src/components/Input/demo/valid.md

**Comment by EvanLai0819** [comment]
好
