### ISSUE TITLE
如何给“日期选择器”动态赋值？

### ISSUE THREAD

**Issue by Jayk1949** [aliqin/atui#24]
比如点击某个按钮，把日期选择器的value 改为 "2017-04-01" ?

**Comment by lynsun** [comment]
v0.1.1后支持了这个特性，可以给datepicker绑定`v-model="dateObj"`，详情参考官网demo：
https://aliqin.github.io/atui/src/components/DatePicker

**Comment by Jayk1949** [comment]
试了下～OK～给个赞～ @lynsun 
其他的form相关组件会不会也加上 v-model 呢？
比如timePicker？

**Comment by lynsun** [comment]
DatePicker，Calendar, RangePicker目前都支持`v-model`的，TimePicker的下个版本支持下
