### ISSUE TITLE
Modal组件里面使用Select组件出现的问题

### ISSUE THREAD

**Issue by jeromyZ** [aliqin/atui#26]
Modal组件里的类“.atui-modal-dialog”有用到transfrom属性定位居中，点击内部Select组件触发小图标旋转动画同时会触发类“.atui-modal-dialog”的transfrom属性

**Comment by chaoren1641** [comment]
抱歉，问题拖得有点久，验证了一把并没有异常情况，如果问题还在请描述清楚导致的影响现象是什么并重新开一个issue，再次抱歉！
