### ISSUE TITLE
table 在调用分页的时候 数据少一条

### ISSUE THREAD

**Issue by yupengRoy** [aliqin/atui#27]

**Comment by chaoren1641** [comment]
请按照以下格式提供更详细的信息，方便我们排查，多谢！

-------------------
ATUI版本:

操作系统版本 / 浏览器版本:

Vue 版本:

关键代码或在线demo（比如jsfiddle、codepen）:

**Comment by yupengRoy** [comment]
"atui": "^0.1.1"
"vue": "^2.2.2"
win7x64 & chrome57.0.2987.98
<v-table :data-source="list" :columns="title" :row-selection="rowSelection" row-key="key" :loading=false  :pagination="pagination" >
					<template scope="props" slot="operation">
					    <v-button primary>操作</v-button>
					</template>
				</v-table>

data:
title:[
	        	{
					title: '姓名',
					dataIndex: 'name',
					key: 'name'
				},
				{
					title: '年龄',
					dataIndex: 'age',
					key: 'age'
				},
				{
					title: '住址',
					dataIndex: 'address',
					key: 'address'
				},
				{
					title: '操作',
					dataIndex: 'operation',
					key: 'operation'
				}
        	],
         	list: [
         			{
						key: '1',
					  	name: '胡彦斌',
					  	age: 3,
					  	address: '西湖区湖底公园1号'
					},
					{
					 	key: '2',
					 	name: '胡彦祖',
					 	age: 4,
					 	address: '西湖区湖底公园1号'
					},
					{
					 	key: '3',
					 	name: '胡彦祖',
					 	age: 5,
					 	address: '西湖区湖底公园1号'
					},
					{
					 	key: '4',
					 	name: '胡彦祖',
					 	age: 42,
					 	address: '西湖区湖底公园1号'
					},
					{
					 	key: '5',
					 	name: '胡彦祖',
					 	age: 42,
					 	address: '西湖区湖底公园1号'
					},
					{
					 	key: '6',
					 	name: '胡彦祖',
					 	age: 42,
					 	address: '西湖区湖底公园1号'
					},
					{
					 	key: '7',
					 	name: '胡彦祖',
					 	age: 42,
					 	address: '西湖区湖底公园1号'
					},
					{
					 	key: '8',
					 	name: '胡彦祖',
					 	age: 42,
					 	address: '西湖区湖底公园1号'
					},
					{
					 	key: '9',
					 	name: '胡彦祖',
					 	age: 42,
					 	address: '西湖区湖底公园1号'
					},
					{
					 	key: '10',
					 	name: '胡彦祖',
					 	age: 42,
					 	address: '西湖区湖底公园1号'
					},
					{
					 	key: '11',
					 	name: '胡彦祖',
					 	age: 42,
					 	address: '西湖区湖底公园1号'
					},
					{
					 	key: '12',
					 	name: '胡彦祖',
					 	age: 42,
					 	address: '西湖区湖底公园1号'
					},
					{
					 	key: '13',
					 	name: '胡彦祖',
					 	age: 60,
					 	address: '西湖区湖底公园1号'
					}
			]

pagination: {
  total: 13,
  pageSize: 5,
  currPage: 1
}
