### ISSUE TITLE
Menu动态渲染的数据结构,怎么获取selectedKey?

### ISSUE THREAD

**Issue by SimpleNice** [aliqin/atui#38]
### 关键代码或在线demo（比如jsfiddle、codepen） 使用了官方的demo https://raw.githubusercontent.com/aliqin/atui/dev/src/components/Menu/demo/data.md

**Comment by chaoren1641** [comment]
sorry，这是一个bug，之前无法动态获取selectedKey，已经在0.1.31版中修复 https://github.com/aliqin/atui/releases/tag/v0.1.31
