### ISSUE TITLE
Trigger 触发器演示bug

### ISSUE THREAD

**Issue by icebns** [aliqin/atui#42]
![46](https://user-images.githubusercontent.com/37243447/45158990-21c02580-b218-11e8-9cf2-3729c850f17d.png)
当观看过关于Trigger 触发器并点过里面的那些演示之后，切换其他页面会有遗留，刷新也不会消失。

**Comment by chaoren1641** [comment]
**这是个已知bug，抽空修一下 😂**

**Comment by icebns** [comment]
还有一个。。Layout 布局下面管理中心部分，点击导航一下面的选项二会展开导航二joy。。噗

**Comment by chaoren1641** [comment]
fixed via https://github.com/aliqin/atui/commit/f145718371d1a05d1e43fe6cd95f7795e0a2a2b9#diff-2f09db0d0102cd36f120a590ddd831baR34
