### ISSUE TITLE
TimePicker 组件是否可以增加分、秒选择时间为0-59的设置？

### ISSUE THREAD

**Issue by 747969780** [aliqin/atui#43]
![image](https://user-images.githubusercontent.com/29268460/53778316-3c5d2800-3f37-11e9-9963-af91cf8f4713.png)

目前是只有1-60，其实有点反人类..是否可以增加一个设置，设置为0-59呢

像这样

![image](https://user-images.githubusercontent.com/29268460/53778347-5dbe1400-3f37-11e9-8287-5d1dc93f026c.png)

**Comment by chaoren1641** [comment]
已修复
via https://github.com/aliqin/atui/commit/f145718371d1a05d1e43fe6cd95f7795e0a2a2b9#diff-2f09db0d0102cd36f120a590ddd831baR34
