### ISSUE TITLE
运行不起来

### ISSUE THREAD

**Issue by yuu2lee4** [aliqin/atui#6]
想贡献代码都不行 貌似是shell的东西？

**Comment by lynsun** [comment]
请问下你是在windows下开发还是linux/mac下，项目跑不起来是有什么报错

**Comment by yuu2lee4** [comment]
mac 有贡献指南之类的么

**Comment by lynsun** [comment]
clone下来后拉一个分支，安装依赖包后执行npm run start启动服务，通过http://localhost:8001/访问组件官网，每个组件目录下的demo目录中每个markdown文件就对应一个demo，可以一边改组件一边看demo的展示，试下

**Comment by yuu2lee4** [comment]
3q  可以了。。。可能是开始依赖没装好。。。
