### ISSUE TITLE
table- fail to display the Table in 360 BROWSER(6.3.1.134)

### ISSUE THREAD

**Issue by ql434** [aliqin/atui#9]
* 360 Browser version :![default](https://cloud.githubusercontent.com/assets/7567247/22285090/2d11a490-e325-11e6-8597-9e28470b2a1d.png)
* Chrome :
![2](https://cloud.githubusercontent.com/assets/7567247/22285292/fc54df74-e325-11e6-9cfc-f4d65f35fdbe.png)
* 360 :
![1](https://cloud.githubusercontent.com/assets/7567247/22285303/1109664c-e326-11e6-8a4e-6125333f6083.png)

**Comment by lynsun** [comment]
v8.x is ok
